/* =============================================================
   Kora Editor — serializer.js
   Serializes / deserializes the scene state and generates KScript.
============================================================= */
'use strict';

// ------------------------------------------------------------------
// JSON  ↔  Scene
// ------------------------------------------------------------------

/**
 * Serialize the current entity array to a plain JSON-safe object.
 * @param {object[]} entities
 * @param {object}   meta        – { name, version, logicalW, logicalH, parentScene }
 * @returns {object} scene document
 */
function sceneToJSON(entities, meta = {}) {
  // Build tree from flat list with parentId
  const childrenMap = {};
  const roots = [];
  entities.forEach(e => {
    if (e.parentId) {
      if (!childrenMap[e.parentId]) childrenMap[e.parentId] = [];
      childrenMap[e.parentId].push(e);
    } else {
      roots.push(e);
    }
  });
  function entityToObj(e) {
    const obj = {
      id:       e.id,
      name:     e.name,
      type:     e.type,
      x:        e.x,
      y:        e.y,
      w:        e.w,
      h:        e.h,
      rotation: e.rotation,
      visible:  e.visible,
      locked:   e.locked,
      color:    e.color,
      assetId:  e.assetId || '',
      script:   e.script || '',
    };
    if (childrenMap[e.id]) {
      obj.children = childrenMap[e.id].map(child => entityToObj(child));
    }
    return obj;
  }
  const doc = {
    meta: {
      name:     meta.name    || 'Untitled',
      version:  meta.version || 1,
      logicalW: meta.logicalW || 360,
      logicalH: meta.logicalH || 640,
    },
    entities: roots.map(e => entityToObj(e)),
  };
  if (meta.parentScene) {
    doc.parentScene = meta.parentScene;
  }
  return doc;
}

/**
 * Deserialize a JSON scene document back to an entity array.
 * Re-assigns new sequential ids to avoid conflicts.
 * @param {object}   doc        – parsed JSON scene document
 * @param {function} nextId     – () => number  (id generator)
 * @returns {{ entities: object[], meta: object }}
 */
function jsonToScene(doc, nextId) {
  const meta = doc.meta || {};
  if (!meta.name && !doc.name) {
    throw new Error('Formato de cena inválido ou versão incompatível.');
  }
  const entities = [];
  function processEntity(e, parentId) {
    const ent = {
      id:       nextId(),
      name:     e.name     || 'Entity',
      type:     e.type     || 'custom',
      x:        Number(e.x)        || 0,
      y:        Number(e.y)        || 0,
      w:        Number(e.w)        || 48,
      h:        Number(e.h)        || 48,
      rotation: Number(e.rotation) || 0,
      visible:  e.visible !== false,
      locked:   !!e.locked,
      color:    e.color    || '#00e5a0',
      assetId:  e.assetId  || '',
      script:   e.script   || '',
      parentId: parentId || null,
    };
    entities.push(ent);
    // Process children if present
    if (e.children && Array.isArray(e.children)) {
      e.children.forEach(child => processEntity(child, ent.id));
    }
    // Fallback to parentId field (flat format)
    if (e.parentId && !e.children) {
      ent.parentId = e.parentId;
    }
  }
  (doc.entities || []).forEach(e => processEntity(e, null));
  return {
    entities,
    meta: {
      name:       meta.name     || doc.name     || 'Untitled',
      version:    meta.version  || doc.version  || 1,
      logicalW:   meta.logicalW || doc.logicalW || 360,
      logicalH:   meta.logicalH || doc.logicalH || 640,
      parentScene: doc.parentScene || '',
    },
  };
}

// ------------------------------------------------------------------
// KScript code generation
// ------------------------------------------------------------------

const KSCRIPT_TYPE_MAP = {
  sprite:  'SpriteEntity',
  tilemap: 'TilemapEntity',
  camera:  'CameraEntity',
  audio:   'AudioEmitter',
  custom:  'Entity',
};

/**
 * Generate a .ks source file from an entity array.
 * @param {object[]} entities
 * @param {string}   sceneName
 * @returns {string} KScript source
 */
function sceneToKScript(entities, sceneName = 'GameScene') {
  const lines = [];

  lines.push(`// Generated by Kora Editor — ${new Date().toISOString()}`);
  lines.push(`// Scene: ${sceneName}`);
  lines.push('');

  // Entity class declarations
  for (const e of entities) {
    const typeName = KSCRIPT_TYPE_MAP[e.type] || 'Entity';
    const className = sanitizeIdent(e.name);

    lines.push(`entity ${className} : ${typeName} {`);
    lines.push(`  x        = ${e.x}`);
    lines.push(`  y        = ${e.y}`);
    lines.push(`  width    = ${e.w}`);
    lines.push(`  height   = ${e.h}`);
    lines.push(`  rotation = ${e.rotation}`);
    lines.push(`  visible  = ${e.visible}`);
    if (e.color) {
      lines.push(`  color    = "${e.color}"`);
    }
    lines.push('');

    if (e.script && e.script.trim()) {
      // Indent embedded script block
      const scriptLines = e.script.trim().split('\n');
      for (const sl of scriptLines) {
        lines.push('  ' + sl);
      }
      lines.push('');
    }

    lines.push('}');
    lines.push('');
  }

  // Scene factory — spawns all entities
  lines.push(`scene ${sanitizeIdent(sceneName)} {`);
  for (const e of entities) {
    if (e.visible) {
      lines.push(`  spawn ${sanitizeIdent(e.name)}()`);
    }
  }
  lines.push('}');
  lines.push('');

  return lines.join('\n');
}

// ------------------------------------------------------------------
// Helpers
// ------------------------------------------------------------------

/**
 * Convert an arbitrary string to a valid KScript identifier.
 * e.g. "My Entity 2!" → "MyEntity2"
 */
function sanitizeIdent(str) {
  return str
    .replace(/[^a-zA-Z0-9_]/g, '_')
    .replace(/^([0-9])/, '_$1');
}

// ------------------------------------------------------------------
// File I/O  (browser)
// ------------------------------------------------------------------

/** Trigger a JSON file download in the browser. */
function downloadJSON(doc, filename = 'scene.kora.json') {
  const blob = new Blob([JSON.stringify(doc, null, 2)], { type: 'application/json' });
  triggerDownload(blob, filename);
}

/** Trigger a KScript file download in the browser. */
function downloadKScript(source, filename = 'scene.ks') {
  const blob = new Blob([source], { type: 'text/plain' });
  triggerDownload(blob, filename);
}

function triggerDownload(blob, filename) {
  const url = URL.createObjectURL(blob);
  const a   = document.createElement('a');
  a.href     = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * Open a file-picker and return the parsed JSON (Promise).
 * Rejects if the file is not valid JSON or not a .kora.json.
 */
function openSceneFile() {
  return new Promise((resolve, reject) => {
    const input = document.createElement('input');
    input.type   = 'file';
    input.accept = '.json,.kora.json';
    input.addEventListener('change', async () => {
      const file = input.files[0];
      if (!file) return reject(new Error('Nenhum arquivo selecionado.'));
      try {
        const text = await file.text();
        const doc  = JSON.parse(text);
        resolve(doc);
      } catch (err) {
        reject(new Error('Arquivo inválido: ' + err.message));
      }
    });
    input.click();
  });
}

// ------------------------------------------------------------------
// Exports (used by editor.js via global)
// ------------------------------------------------------------------
window.Serializer = {
  sceneToJSON,
  jsonToScene,
  sceneToKScript,
  downloadJSON,
  downloadKScript,
  openSceneFile,
  sanitizeIdent,
};
