// Package emitter generates Go source code from a type-checked, transformed
// KScript AST. Each KScript `object` becomes a Go struct. Async methods
// compile to Task structs implementing core/async.Task.
package emitter

import (
	"fmt"
	"strings"

	"github.com/ElioNeto/kora/compiler/ast"
	"github.com/ElioNeto/kora/compiler/transform"
)

// Options configures code generation.
type Options struct {
	// Package is the Go package name to emit (default: "gen").
	Package string
	// RuntimeImport is the module path for the Kora runtime.
	RuntimeImport string
}

func defaultOptions() Options {
	return Options{
		Package:       "gen",
		RuntimeImport: "github.com/ElioNeto/kora/core",
	}
}

// Emitter converts a KScript Program + async transform map into Go source.
type Emitter struct {
	opts      Options
	asyncMap  map[*ast.MethodDecl]*transform.AsyncMethod
	prog      *ast.Program
	out       strings.Builder
	indent    int
}

// New creates an Emitter.
func New(prog *ast.Program, asyncMap map[*ast.MethodDecl]*transform.AsyncMethod, opts *Options) *Emitter {
	o := defaultOptions()
	if opts != nil {
		if opts.Package != "" {
			o.Package = opts.Package
		}
		if opts.RuntimeImport != "" {
			o.RuntimeImport = opts.RuntimeImport
		}
	}
	return &Emitter{opts: o, asyncMap: asyncMap, prog: prog}
}

// Emit generates and returns the Go source file as a string.
func (e *Emitter) Emit() string {
	e.emitHeader()
	for _, obj := range e.prog.Objects {
		e.emitObject(obj)
	}
	return e.out.String()
}

// ---------------------------------------------------------------------------
// File header
// ---------------------------------------------------------------------------

func (e *Emitter) emitHeader() {
	e.line("// Code generated by the Kora KScript compiler. DO NOT EDIT.")
	e.line("")
	e.linef("package %s", e.opts.Package)
	e.line("")
	e.line("import (")
	e.push()
	e.linef(`"github.com/ElioNeto/kora/core/async"`)
	e.linef(`"github.com/ElioNeto/kora/core/render"`)
	e.pop()
	e.line(")")
	e.line("")
	e.line("// Suppress unused import errors during early development.")
	e.line("var _ = async.Wait")
	e.line("var _ = (*render.Renderer)(nil)")
	e.line("")
}

// ---------------------------------------------------------------------------
// Object → Go struct
// ---------------------------------------------------------------------------

func (e *Emitter) emitObject(obj *ast.ObjectDecl) {
	e.linef("// %s is a KScript object.", obj.Name)
	e.linef("type %s struct {", obj.Name)
	e.push()

	// Built-in entity fields.
	e.line("X, Y         float64")
	e.line("VelX, VelY   float64")
	e.line("Alpha        float32")
	e.line("Visible      bool")
	e.line("Tag          string")
	e.line("alive        bool")

	// User-declared fields.
	for _, f := range obj.Fields {
		goType := ksTypeToGo(f.Type)
		e.linef("%s %s", capitalize(f.Name), goType)
	}
	e.pop()
	e.line("}")
	e.line("")

	// Constructor.
	e.linef("func New%s() *%s {", obj.Name, obj.Name)
	e.push()
	e.linef("o := &%s{alive: true, Visible: true, Alpha: 1.0}", obj.Name)
	for _, f := range obj.Fields {
		if f.Default != nil {
			e.linef("o.%s = %s", capitalize(f.Name), e.emitExprStr(f.Default))
		}
	}
	e.line("return o")
	e.pop()
	e.line("}")
	e.line("")

	// scene.Entity interface.
	e.linef("func (o *%s) IsAlive() bool { return o.alive }", obj.Name)
	e.linef("func (o *%s) Destroy()     { o.alive = false }", obj.Name)
	e.line("")

	// Methods.
	for _, m := range obj.Methods {
		if m.Async {
			if am, ok := e.asyncMap[m]; ok {
				e.emitAsyncMethod(obj, m, am)
			}
		} else {
			e.emitSyncMethod(obj, m)
		}
	}
}

// ---------------------------------------------------------------------------
// Sync method
// ---------------------------------------------------------------------------

func (e *Emitter) emitSyncMethod(obj *ast.ObjectDecl, m *ast.MethodDecl) {
	params := e.formatParams(m.Params)
	ret := ""
	if m.Return != "" && m.Return != "void" {
		ret = " " + ksTypeToGo(m.Return)
	}

	// Lifecycle methods map to the scene.Entity interface.
	switch m.Name {
	case "update":
		e.linef("func (o *%s) Update(%s)%s {", obj.Name, params, ret)
	case "draw":
		e.linef("func (o *%s) Draw(r *render.Renderer)%s {", obj.Name, ret)
	default:
		e.linef("func (o *%s) %s(%s)%s {", obj.Name, capitalize(m.Name), params, ret)
	}
	e.push()
	for _, stmt := range m.Body {
		e.emitStmt(stmt)
	}
	e.pop()
	e.line("}")
	e.line("")
}

// ---------------------------------------------------------------------------
// Async method → state machine struct
// ---------------------------------------------------------------------------

func (e *Emitter) emitAsyncMethod(obj *ast.ObjectDecl, m *ast.MethodDecl, am *transform.AsyncMethod) {
	smName := fmt.Sprintf("%s_%s_Task", obj.Name, capitalize(m.Name))

	// State machine struct.
	e.linef("// %s is the compiled state machine for %s.%s.", smName, obj.Name, m.Name)
	e.linef("type %s struct {", smName)
	e.push()
	e.linef("owner    *%s", obj.Name)
	e.line("state    int")
	e.line("subtask  async.Task")
	for _, lv := range am.LiveVars {
		e.linef("%s %s", lv.Name, ksTypeToGo(lv.Type))
	}
	e.pop()
	e.line("}")
	e.line("")

	// Tick method — the state machine dispatcher.
	e.linef("func (t *%s) Tick(dt float64) async.Status {", smName)
	e.push()
	e.line("for {")
	e.push()
	e.line("switch t.state {")

	for i, state := range am.States {
		e.linef("case %d:", i)
		e.push()

		// Advance sub-task if we are waiting on one.
		if i > 0 {
			e.line("if t.subtask != nil {")
			e.push()
			e.line("if t.subtask.Tick(dt) != async.Done {")
			e.push()
			e.line("return async.Running")
			e.pop()
			e.line("}")
			e.line("t.subtask = nil")
			e.pop()
			e.line("}")
		}

		// Emit synchronous statements for this state.
		for _, stmt := range state.Stmts {
			e.emitStmt(stmt)
		}

		if state.Await != nil {
			// Launch sub-task and advance state.
			e.linef("t.subtask = %s", e.emitExprStr(state.Await))
			e.linef("t.state = %d", i+1)
		} else {
			// Terminal state.
			e.line("return async.Done")
		}
		e.pop()
	}

	e.line("default:")
	e.push()
	e.line("return async.Done")
	e.pop()

	e.line("}")
	e.pop()
	e.line("}")
	e.pop()
	e.line("}")
	e.line("")

	// Launcher method on owner struct.
	e.linef("func (o *%s) %s() *%s {", obj.Name, capitalize(m.Name), smName)
	e.push()
	e.linef("return &%s{owner: o, state: 0}", smName)
	e.pop()
	e.line("}")
	e.line("")
}

// ---------------------------------------------------------------------------
// Statement emitter
// ---------------------------------------------------------------------------

func (e *Emitter) emitStmt(stmt ast.Stmt) {
	switch s := stmt.(type) {
	case *ast.VarStmt:
		if s.Value != nil {
			e.linef("%s := %s", s.Name, e.emitExprStr(s.Value))
		} else {
			e.linef("var %s %s", s.Name, ksTypeToGo(s.Type))
		}
	case *ast.AssignStmt:
		e.linef("%s %s %s", e.emitExprStr(s.Target), s.Op, e.emitExprStr(s.Value))
	case *ast.ReturnStmt:
		if s.Value != nil {
			e.linef("return %s", e.emitExprStr(s.Value))
		} else {
			e.line("return")
		}
	case *ast.ExprStmt:
		e.linef("%s", e.emitExprStr(s.X))
	case *ast.IfStmt:
		e.linef("if %s {", e.emitExprStr(s.Cond))
		e.push()
		for _, st := range s.Then {
			e.emitStmt(st)
		}
		e.pop()
		if len(s.Else) > 0 {
			e.line("} else {")
			e.push()
			for _, st := range s.Else {
				e.emitStmt(st)
			}
			e.pop()
		}
		e.line("}")
	case *ast.WhileStmt:
		e.linef("for %s {", e.emitExprStr(s.Cond))
		e.push()
		for _, st := range s.Body {
			e.emitStmt(st)
		}
		e.pop()
		e.line("}")
	case *ast.BreakStmt:
		e.line("break")
	case *ast.ContinueStmt:
		e.line("continue")
	case *ast.AwaitStmt:
		// Inside the state machine this is handled by the transformer.
		// If it appears in sync context (checker prevents this), emit a comment.
		e.linef("/* await %s */", e.emitExprStr(s.Task))
	case *ast.EmitStmt:
		e.linef(`o.EmitSignal(%q)`, s.Signal)
	}
}

// ---------------------------------------------------------------------------
// Expression emitter
// ---------------------------------------------------------------------------

func (e *Emitter) emitExprStr(expr ast.Expr) string {
	if expr == nil {
		return ""
	}
	switch ex := expr.(type) {
	case *ast.IntLit:
		return fmt.Sprintf("%d", ex.Value)
	case *ast.FloatLit:
		return fmt.Sprintf("%g", ex.Value)
	case *ast.BoolLit:
		if ex.Value {
			return "true"
		}
		return "false"
	case *ast.StringLit:
		return fmt.Sprintf("%q", ex.Value)
	case *ast.NullLit:
		return "nil"
	case *ast.ThisExpr:
		return "o"
	case *ast.Ident:
		return ex.Name
	case *ast.BinaryExpr:
		return fmt.Sprintf("(%s %s %s)",
			e.emitExprStr(ex.Left), ex.Op, e.emitExprStr(ex.Right))
	case *ast.UnaryExpr:
		return fmt.Sprintf("%s%s", ex.Op, e.emitExprStr(ex.Operand))
	case *ast.CallExpr:
		args := make([]string, len(ex.Args))
		for i, a := range ex.Args {
			args[i] = e.emitExprStr(a)
		}
		callee := e.emitExprStr(ex.Callee)
		// Qualify built-in async functions with async. package
		switch callee {
		case "wait", "waitFrames", "waitSignal", "tween", "race", "all", "cancel":
			callee = "async." + capitalize(callee)
		}
		return fmt.Sprintf("%s(%s)", callee, strings.Join(args, ", "))
	case *ast.MemberExpr:
		obj := e.emitExprStr(ex.Object)
		// `this.x` → `o.X` (capitalize field name)
		if _, isThis := ex.Object.(*ast.ThisExpr); isThis {
			return fmt.Sprintf("%s.%s", obj, capitalize(ex.Prop))
		}
		return fmt.Sprintf("%s.%s", obj, ex.Prop)
	case *ast.IndexExpr:
		return fmt.Sprintf("%s[%s]", e.emitExprStr(ex.Object), e.emitExprStr(ex.Index))
	}
	return "/* unknown expr */"
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

func (e *Emitter) line(s string) {
	e.out.WriteString(strings.Repeat("\t", e.indent))
	e.out.WriteString(s)
	e.out.WriteByte('\n')
}

func (e *Emitter) linef(format string, args ...any) {
	e.line(fmt.Sprintf(format, args...))
}

func (e *Emitter) push() { e.indent++ }
func (e *Emitter) pop()  { e.indent-- }

func (e *Emitter) formatParams(params []*ast.Param) string {
	parts := make([]string, len(params))
	for i, p := range params {
		parts[i] = fmt.Sprintf("%s %s", p.Name, ksTypeToGo(p.Type))
	}
	return strings.Join(parts, ", ")
}

// ksTypeToGo maps a KScript type name to its Go equivalent.
func ksTypeToGo(t string) string {
	switch t {
	case "int":
		return "int"
	case "float":
		return "float64"
	case "bool":
		return "bool"
	case "string":
		return "string"
	case "void":
		return ""
	case "Task":
		return "async.Task"
	case "Entity":
		return "scene.Entity"
	case "Vec2":
		return "render.Vec2"
	case "int[]":
		return "[]int"
	case "float[]":
		return "[]float64"
	case "string[]":
		return "[]string"
	case "Entity[]":
		return "[]scene.Entity"
	case "any", "":
		return "interface{}"
	default:
		return t // user-defined object types pass through
	}
}

// capitalize uppercases the first rune of s.
func capitalize(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}
